/* DO NOT EDIT, please edit generator instead.
   This file was generated by gen-vector-iterator with the command:
   $ ./gen-vector-iterator -c > riscv-vector-iterator.h  */
/* An iterator to call a macro with every supported SEW and LMUL,
   along with its corresponding vector and scalar modes in GCC.  */
#define _RVV_INT_TYPE_ITERATOR(MACRO) \
  MACRO (8, 1, VNx16QI, QI) \
  MACRO (8, 2, VNx32QI, QI) \
  MACRO (8, 4, VNx64QI, QI) \
  MACRO (8, 8, VNx128QI, QI) \
  MACRO (16, 1, VNx8HI, HI) \
  MACRO (16, 2, VNx16HI, HI) \
  MACRO (16, 4, VNx32HI, HI) \
  MACRO (16, 8, VNx64HI, HI) \
  MACRO (32, 1, VNx4SI, SI) \
  MACRO (32, 2, VNx8SI, SI) \
  MACRO (32, 4, VNx16SI, SI) \
  MACRO (32, 8, VNx32SI, SI) \
  MACRO (64, 1, VNx2DI, DI) \
  MACRO (64, 2, VNx4DI, DI) \
  MACRO (64, 4, VNx8DI, DI) \
  MACRO (64, 8, VNx16DI, DI) \

/* Same as above but with an extra argument.  */
#define _RVV_INT_TYPE_ITERATOR_ARG(MACRO, ...) \
  MACRO (8, 1, VNx16QI, QI, __VA_ARGS__) \
  MACRO (8, 2, VNx32QI, QI, __VA_ARGS__) \
  MACRO (8, 4, VNx64QI, QI, __VA_ARGS__) \
  MACRO (8, 8, VNx128QI, QI, __VA_ARGS__) \
  MACRO (16, 1, VNx8HI, HI, __VA_ARGS__) \
  MACRO (16, 2, VNx16HI, HI, __VA_ARGS__) \
  MACRO (16, 4, VNx32HI, HI, __VA_ARGS__) \
  MACRO (16, 8, VNx64HI, HI, __VA_ARGS__) \
  MACRO (32, 1, VNx4SI, SI, __VA_ARGS__) \
  MACRO (32, 2, VNx8SI, SI, __VA_ARGS__) \
  MACRO (32, 4, VNx16SI, SI, __VA_ARGS__) \
  MACRO (32, 8, VNx32SI, SI, __VA_ARGS__) \
  MACRO (64, 1, VNx2DI, DI, __VA_ARGS__) \
  MACRO (64, 2, VNx4DI, DI, __VA_ARGS__) \
  MACRO (64, 4, VNx8DI, DI, __VA_ARGS__) \
  MACRO (64, 8, VNx16DI, DI, __VA_ARGS__) \

/* An iterator to call a macro with every supported SEW and LMUL,
   along with its corresponding vector and scalar modes in GCC.  */
#define _RVV_FLOAT_TYPE_ITERATOR(MACRO) \
  MACRO (16, 1, VNx8HF, HF) \
  MACRO (16, 2, VNx16HF, HF) \
  MACRO (16, 4, VNx32HF, HF) \
  MACRO (16, 8, VNx64HF, HF) \
  MACRO (32, 1, VNx4SF, SF) \
  MACRO (32, 2, VNx8SF, SF) \
  MACRO (32, 4, VNx16SF, SF) \
  MACRO (32, 8, VNx32SF, SF) \
  MACRO (64, 1, VNx2DF, DF) \
  MACRO (64, 2, VNx4DF, DF) \
  MACRO (64, 4, VNx8DF, DF) \
  MACRO (64, 8, VNx16DF, DF) \

/* Same as above but with an extra argument.  */
#define _RVV_FLOAT_TYPE_ITERATOR_ARG(MACRO, ...) \
  MACRO (16, 1, VNx8HF, HF, __VA_ARGS__) \
  MACRO (16, 2, VNx16HF, HF, __VA_ARGS__) \
  MACRO (16, 4, VNx32HF, HF, __VA_ARGS__) \
  MACRO (16, 8, VNx64HF, HF, __VA_ARGS__) \
  MACRO (32, 1, VNx4SF, SF, __VA_ARGS__) \
  MACRO (32, 2, VNx8SF, SF, __VA_ARGS__) \
  MACRO (32, 4, VNx16SF, SF, __VA_ARGS__) \
  MACRO (32, 8, VNx32SF, SF, __VA_ARGS__) \
  MACRO (64, 1, VNx2DF, DF, __VA_ARGS__) \
  MACRO (64, 2, VNx4DF, DF, __VA_ARGS__) \
  MACRO (64, 4, VNx8DF, DF, __VA_ARGS__) \
  MACRO (64, 8, VNx16DF, DF, __VA_ARGS__) \

