/* DO NOT EDIT, please edit generator instead.
   This file was generated by gen-vector-iterator with the command:
   $ ./gen-vector-iterator -c > riscv-vector-iterator.h  */
/* An iterator to call a macro with every supported SEW and LMUL,
   along with its corresponding vector and scalar modes in GCC.  */
#define _RVV_INT_TYPE_ITERATOR(MACRO) \
  MACRO (8, 1, VNx16QI, QI, VNx16BI) \
  MACRO (8, 2, VNx32QI, QI, VNx32BI) \
  MACRO (8, 4, VNx64QI, QI, VNx64BI) \
  MACRO (8, 8, VNx128QI, QI, VNx128BI) \
  MACRO (16, 1, VNx8HI, HI, VNx8BI) \
  MACRO (16, 2, VNx16HI, HI, VNx16BI) \
  MACRO (16, 4, VNx32HI, HI, VNx32BI) \
  MACRO (16, 8, VNx64HI, HI, VNx64BI) \
  MACRO (32, 1, VNx4SI, SI, VNx4BI) \
  MACRO (32, 2, VNx8SI, SI, VNx8BI) \
  MACRO (32, 4, VNx16SI, SI, VNx16BI) \
  MACRO (32, 8, VNx32SI, SI, VNx32BI) \
  MACRO (64, 1, VNx2DI, DI, VNx2BI) \
  MACRO (64, 2, VNx4DI, DI, VNx4BI) \
  MACRO (64, 4, VNx8DI, DI, VNx8BI) \
  MACRO (64, 8, VNx16DI, DI, VNx16BI) \

/* Same as above but with an extra argument.  */
#define _RVV_INT_TYPE_ITERATOR_ARG(MACRO, ...) \
  MACRO (8, 1, VNx16QI, QI, VNx16BI, __VA_ARGS__) \
  MACRO (8, 2, VNx32QI, QI, VNx32BI, __VA_ARGS__) \
  MACRO (8, 4, VNx64QI, QI, VNx64BI, __VA_ARGS__) \
  MACRO (8, 8, VNx128QI, QI, VNx128BI, __VA_ARGS__) \
  MACRO (16, 1, VNx8HI, HI, VNx8BI, __VA_ARGS__) \
  MACRO (16, 2, VNx16HI, HI, VNx16BI, __VA_ARGS__) \
  MACRO (16, 4, VNx32HI, HI, VNx32BI, __VA_ARGS__) \
  MACRO (16, 8, VNx64HI, HI, VNx64BI, __VA_ARGS__) \
  MACRO (32, 1, VNx4SI, SI, VNx4BI, __VA_ARGS__) \
  MACRO (32, 2, VNx8SI, SI, VNx8BI, __VA_ARGS__) \
  MACRO (32, 4, VNx16SI, SI, VNx16BI, __VA_ARGS__) \
  MACRO (32, 8, VNx32SI, SI, VNx32BI, __VA_ARGS__) \
  MACRO (64, 1, VNx2DI, DI, VNx2BI, __VA_ARGS__) \
  MACRO (64, 2, VNx4DI, DI, VNx4BI, __VA_ARGS__) \
  MACRO (64, 4, VNx8DI, DI, VNx8BI, __VA_ARGS__) \
  MACRO (64, 8, VNx16DI, DI, VNx16BI, __VA_ARGS__) \

/* An iterator to call a macro with every supported SEW and LMUL,
   along with its corresponding vector and scalar modes in GCC.  */
#define _RVV_FLOAT_TYPE_ITERATOR(MACRO) \
  MACRO (16, 1, VNx8HF, HF, VNx8BI) \
  MACRO (16, 2, VNx16HF, HF, VNx16BI) \
  MACRO (16, 4, VNx32HF, HF, VNx32BI) \
  MACRO (16, 8, VNx64HF, HF, VNx64BI) \
  MACRO (32, 1, VNx4SF, SF, VNx4BI) \
  MACRO (32, 2, VNx8SF, SF, VNx8BI) \
  MACRO (32, 4, VNx16SF, SF, VNx16BI) \
  MACRO (32, 8, VNx32SF, SF, VNx32BI) \
  MACRO (64, 1, VNx2DF, DF, VNx2BI) \
  MACRO (64, 2, VNx4DF, DF, VNx4BI) \
  MACRO (64, 4, VNx8DF, DF, VNx8BI) \
  MACRO (64, 8, VNx16DF, DF, VNx16BI) \

/* Same as above but with an extra argument.  */
#define _RVV_FLOAT_TYPE_ITERATOR_ARG(MACRO, ...) \
  MACRO (16, 1, VNx8HF, HF, VNx8BI, __VA_ARGS__) \
  MACRO (16, 2, VNx16HF, HF, VNx16BI, __VA_ARGS__) \
  MACRO (16, 4, VNx32HF, HF, VNx32BI, __VA_ARGS__) \
  MACRO (16, 8, VNx64HF, HF, VNx64BI, __VA_ARGS__) \
  MACRO (32, 1, VNx4SF, SF, VNx4BI, __VA_ARGS__) \
  MACRO (32, 2, VNx8SF, SF, VNx8BI, __VA_ARGS__) \
  MACRO (32, 4, VNx16SF, SF, VNx16BI, __VA_ARGS__) \
  MACRO (32, 8, VNx32SF, SF, VNx32BI, __VA_ARGS__) \
  MACRO (64, 1, VNx2DF, DF, VNx2BI, __VA_ARGS__) \
  MACRO (64, 2, VNx4DF, DF, VNx4BI, __VA_ARGS__) \
  MACRO (64, 4, VNx8DF, DF, VNx8BI, __VA_ARGS__) \
  MACRO (64, 8, VNx16DF, DF, VNx16BI, __VA_ARGS__) \

