/* Builtin definitions for P extension
   Copyright (C) 2021 Free Software Foundation, Inc.

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#ifndef _RISCV_RVP_INTRINSIC_H
#define _RISCV_RVP_INTRINSIC_H

#if !defined (__riscv_zpn)
#error "Packed SIMD intrinsics require the rvp extension."
#endif

#include <stdint.h>

typedef signed char int8x4_t __attribute ((vector_size(4)));
typedef signed char int8x8_t __attribute ((vector_size(8)));
typedef short int16x2_t __attribute ((vector_size(4)));
typedef short int16x4_t __attribute__((vector_size (8)));
typedef int int32x2_t __attribute__((vector_size(8)));
typedef unsigned char uint8x4_t __attribute__ ((vector_size (4)));
typedef unsigned char uint8x8_t __attribute__ ((vector_size (8)));
typedef unsigned short uint16x2_t __attribute__ ((vector_size (4)));
typedef unsigned short uint16x4_t __attribute__((vector_size (8)));
typedef unsigned int uint32x2_t __attribute__((vector_size(8)));

#if __riscv_xlen == 32
typedef int32_t intXLEN_t;
typedef uint32_t uintXLEN_t;
typedef int32_t int32xN_t;
typedef uint32_t uint32xN_t;
typedef uint16x2_t uint16xN_t;
typedef int16x2_t int16xN_t;
typedef uint8x4_t uint8xN_t;
typedef int8x4_t int8xN_t;
#else
typedef int64_t intXLEN_t;
typedef uint64_t uintXLEN_t;
typedef int32x2_t int32xN_t;
typedef uint32x2_t uint32xN_t;
typedef uint16x4_t uint16xN_t;
typedef int16x4_t int16xN_t;
typedef uint8x8_t uint8xN_t;
typedef int8x8_t int8xN_t;
#endif

#define RVP_INTRINSIC_PREFIX __rv_
#define RVP_INTRINSIC_VECTOR_PREFIX __rv_v_

#define RVP_ARGUMENT_LIST(_0, _1, _2, _3, _4, _5, ...) _5
#define RVP_N_ARG(...) RVP_ARGUMENT_LIST(_, ## __VA_ARGS__, 4, 3, 2, 1, 0)

#define RVP_VAR0(...) 
#define RVP_VAR1(type1) a
#define RVP_VAR2(type1, type2) RVP_VAR1(type1), b
#define RVP_VAR3(type1, type2, type3) RVP_VAR2(type1, type2), c
#define RVP_VAR4(type1, type2, type3, type4) RVP_VAR3(type1, type2, type3), d

#define RVP_ARG0(...) 
#define RVP_ARG1(type1) type1 a
#define RVP_ARG2(type1, type2) RVP_ARG1(type1), type2 b
#define RVP_ARG3(type1, type2, type3) RVP_ARG2(type1, type2), type3 c
#define RVP_ARG4(type1, type2, type3, type4) RVP_ARG3(type1, type2, type3), type4 d

#define RVP_CONCAT_IMPL(x,y)  x ## y
#define RVP_CONCAT(x, y) RVP_CONCAT_IMPL(x, y)
#define RVP_EXPAND_ARGS(...) RVP_CONCAT(RVP_ARG, RVP_N_ARG(__VA_ARGS__)) (__VA_ARGS__)
#define RVP_EXPAND_VARS(...) RVP_CONCAT(RVP_VAR, RVP_N_ARG(__VA_ARGS__)) (__VA_ARGS__)

#if __riscv_xlen == 32
#define RVP_VECTOR_BUILTIN_PREFIX __builtin_riscv_v_
#else
#define RVP_VECTOR_BUILTIN_PREFIX __builtin_riscv_v64_
#endif

#define CREATE_RVP_INTRINSIC(return_type, name, ...)\
  DIRECT_CREATE_RVP_INTRINSIC (return_type, name, name, __rv_,\
      __builtin_riscv_, RVP_EXPAND_ARGS, RVP_EXPAND_VARS, __VA_ARGS__)

#define CREATE_RVP_INTRINSIC_ALIAS(return_type, name, internal_name, ...)\
  DIRECT_CREATE_RVP_INTRINSIC (return_type, name, internal_name, __rv_,\
      __builtin_riscv_, RVP_EXPAND_ARGS, RVP_EXPAND_VARS, __VA_ARGS__)

/* RVP_N_ARG() expands to 0 in c89 */
#define CREATE_RVP_INTRINSIC_EMPTY_ARGS(return_type, name, ...)\
  DIRECT_CREATE_RVP_INTRINSIC (return_type, name, name, \
    RVP_INTRINSIC_PREFIX, __builtin_riscv_, RVP_ARG0, RVP_VAR0, __VA_ARGS__)

#define CREATE_RVP_INTRINSIC_VECTOR(return_type, name, ...)\
  DIRECT_CREATE_RVP_INTRINSIC (return_type, name, name, \
    RVP_INTRINSIC_VECTOR_PREFIX, RVP_VECTOR_BUILTIN_PREFIX, \
    RVP_EXPAND_ARGS, RVP_EXPAND_VARS, __VA_ARGS__)

#define DIRECT_CREATE_RVP_INTRINSIC(return_type, name, internal_name, intrisic_prefix,\
      builtin_prefix, arg_expand_macro, var_expand_macro, ...)\
  __extension__ extern __inline __attribute__ ((__always_inline__, __gnu_inline__, __artificial__)) \
  return_type RVP_CONCAT(intrisic_prefix, name(arg_expand_macro(__VA_ARGS__))) { \
    return RVP_CONCAT(builtin_prefix, internal_name) (var_expand_macro(__VA_ARGS__)); \
  }

/* ZPN */
CREATE_RVP_INTRINSIC (uintXLEN_t, add8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, add16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, ave, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, bitrev, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC_EMPTY_ARGS (void, clrov)
CREATE_RVP_INTRINSIC (uintXLEN_t, clrs8, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, clrs16, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, clrs32, intXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, clz8, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, clz16, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, clz32, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, cmpeq8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, cmpeq16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, cras16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, crsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, insb, uintXLEN_t, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kabs8, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kabs16, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, kabsw, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kadd8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kadd16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, kaddh, int16_t, int16_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kcras16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kcrsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, kdmbb, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, kdmbt, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, kdmtt, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmbb, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmbt, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmtt, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, kdmabb, int32_t, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, kdmabt, int32_t, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, kdmatt, int32_t, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, khm8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, khmx8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, khm16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, khmx16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, khmbb, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, khmbt, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, khmtt, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, v_khmbb, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_khmbt, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_khmtt, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmabb, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmabt, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmatt, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmada, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmaxda, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmads, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmadrs, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmaxds, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmda, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmxda, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmac, intXLEN_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmac_u, intXLEN_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawb, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawb_u, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawb2, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawb2_u, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawt, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawt_u, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawt2, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmawt2_u, intXLEN_t, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmsb, intXLEN_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmsb_u, intXLEN_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmwb2, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmwb2_u, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmwt2, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmmwt2_u, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmsda, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kmsxda, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, ksllw, int32_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ksll8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ksll16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kslra8, uintXLEN_t, const int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kslra8_u, uintXLEN_t, const int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kslra16, uintXLEN_t, const int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kslra16_u, uintXLEN_t, const int32_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kslraw, int32_t, int32_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kslraw_u, int32_t, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kstas16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, kstsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ksub8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ksub16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, ksubh, int16_t, int16_t)
CREATE_RVP_INTRINSIC (int32_t, ksubw, int32_t, int32_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kwmmul, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, kwmmul_u, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, maddr32, int32_t, int32_t, int32_t)
CREATE_RVP_INTRINSIC (int32_t, msubr32, int32_t, int32_t, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pbsad, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pbsada, uintXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pkbt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pkbb16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pktb16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, pktt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, radd8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, radd16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, raddw, int32_t, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, rcras16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, rcrsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC_EMPTY_ARGS (uintXLEN_t, rdov)
CREATE_RVP_INTRINSIC (uintXLEN_t, rstas16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, rstsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, rsub8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, rsub16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, rsubw, int32_t, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sclip8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sclip16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (intXLEN_t, sclip32, intXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, scmple8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, scmple16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, scmplt8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, scmplt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sll8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sll16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smaqa, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smaqa_su, intXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, smax8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, smax16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smbb16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smbt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smtt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smds, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smdrs, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smxds, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, smin8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, smin16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmul, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmul_u, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmwb, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmwb_u, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmwt, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, smmwt_u, intXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, sra_u, intXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sra8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sra8_u, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sra16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sra16_u, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, srl8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, srl8_u, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, srl16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, srl16_u, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, stas16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, stsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sub8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sub16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sunpkd810, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sunpkd820, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sunpkd830, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sunpkd831, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, sunpkd832, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, swap8, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uclip8, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uclip16, uintXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uclip32, intXLEN_t, const uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ucmplt8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ucmple8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ucmplt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ucmple16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukadd8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukadd16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint32_t, ukaddh, uint16_t, uint16_t)
CREATE_RVP_INTRINSIC (uint32_t, ukaddw, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int32_t, kaddw, int32_t, int32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukcras16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukcrsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukstas16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ukstsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uksub8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uksub16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint32_t, uksubh, uint16_t, uint16_t)
CREATE_RVP_INTRINSIC (uint32_t, uksubw, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, umaqa, uintXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, umax8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, umax16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, umin8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, umin16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uradd8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, uradd16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint32_t, uraddw, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, urcras16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, urcrsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, urstas16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, urstsa16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ursub8, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, ursub16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint32_t, ursubw, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, zunpkd810, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, zunpkd820, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, zunpkd830, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, zunpkd831, uintXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, zunpkd832, uintXLEN_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmabb, int32_t, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmabt, int32_t, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int32_t, v_kdmatt, int32_t, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, uadd8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, sadd8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, uadd16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sadd16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, clrs8, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, clrs16, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, clz8, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, clz16, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, scmpeq8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, ucmpeq8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, scmpeq16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ucmpeq16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ucras16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, scras16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ucrsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, scrsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, kabs8, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kabs16, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, kadd8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kadd16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kcras16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kcrsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, khm8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, khmx8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, khm16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, khmx16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmabb, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmabt, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmatt, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmada, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmaxda, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmads, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmadrs, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmaxds, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmda, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmxda, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawb, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawb_u, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawb2, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawb2_u, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawt, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawt_u, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawt2, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmawt2_u, int32xN_t, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmwb2, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmwb2_u, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmwt2, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmmwt2_u, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmsda, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, kmsxda, int32xN_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, ksll8, int8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, ksll16, int16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, kslra8, int8xN_t, int32_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, kslra8_u, int8xN_t, int32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kslra16, int16xN_t, int32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kslra16_u, int16xN_t, int32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kstas16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, kstsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, ksub8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, ksub16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uintXLEN_t, pbsad, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uintXLEN_t, pbsada, uintXLEN_t, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, pkbt16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, pkbb16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, pktb16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, pktt16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, radd8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, radd16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, rcras16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, rcrsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, rstas16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, rstsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, rsub8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, rsub16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, sclip8, int8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sclip16, int16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, scmple8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, scmple16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, scmplt8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, scmplt16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, sll8, uint8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, sll16, uint16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smaqa, int32xN_t, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smaqa_su, int32xN_t, int8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, smax8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, smax16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smbb16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smbt16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smtt16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smds, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smdrs, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smxds, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, smin8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, smin16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smmwb, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smmwb_u, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smmwt, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int32xN_t, smmwt_u, int32xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, sra8, int8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, sra8_u, int8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sra16, int16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sra16_u, int16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, srl8, uint8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, srl8_u, uint8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, srl16, uint16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, srl16_u, uint16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ustas16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sstas16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ustsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sstsa16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, usub8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int8xN_t, ssub8, int8xN_t, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, usub16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, ssub16, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sunpkd810, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sunpkd820, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sunpkd830, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sunpkd831, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int16xN_t, sunpkd832, int8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, swap8, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, uclip8, int8xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, uclip16, int16xN_t, const uint32_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, ucmplt8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, ucmple8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ucmplt16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ucmple16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, ukadd8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ukadd16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ukcras16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ukcrsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ukstas16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ukstsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, uksub8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, uksub16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint32xN_t, umaqa, uint32xN_t, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, umax8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, umax16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, umin8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, umin16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, uradd8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, uradd16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, urcras16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, urcrsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, urstas16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, urstsa16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint8xN_t, ursub8, uint8xN_t, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, ursub16, uint16xN_t, uint16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, zunpkd810, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, zunpkd820, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, zunpkd830, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, zunpkd831, uint8xN_t)
CREATE_RVP_INTRINSIC_VECTOR (uint16xN_t, zunpkd832, uint8xN_t)
/* alias */
__extension__ extern __inline __attribute__ ((__always_inline__, __gnu_inline__, __artificial__))
uintXLEN_t __rv_swap16 (uintXLEN_t a) {
  return __builtin_riscv_pkbt16 (a, a);
}
__extension__ extern __inline __attribute__ ((__always_inline__, __gnu_inline__, __artificial__))
uint16xN_t __rv_v_swap16 (uint16xN_t a) {
  return RVP_CONCAT(RVP_VECTOR_BUILTIN_PREFIX, pkbt16) (a, a);
}

/* ZPN64 ONLY */
#if __riscv_xlen == 64
CREATE_RVP_INTRINSIC (int32_t, sraw_u, int32_t, const uint32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kabs32, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kadd32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kcras32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kcrsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmabb16, int32x2_t, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmabt16, int32x2_t, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmatt16, int32x2_t, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmbb16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmbt16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kdmtt16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_khmbb16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_khmbt16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_khmtt16, int16x4_t, int16x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kmmac, int32x2_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kmmac_u, int32x2_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kmmsb, int32x2_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kmmsb_u, int32x2_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_ksll32, int32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kslra32, int32x2_t, int32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kslra32_u, int32x2_t, int32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kstas32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kstsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_ksub32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kwmmul, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_kwmmul_u, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_radd32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_rcras32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_rcrsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_rstas32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_rstsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_rsub32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sadd32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sclip32, int32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_scras32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_scrsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_smax32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_smin32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_smmul, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_smmul_u, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sra32, int32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sra32_u, int32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sstas32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_sstsa32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_ssub32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, khmbb16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, khmbt16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, khmtt16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, kmabb32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmabt32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmatt32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmadrs32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmads32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmaxda32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmaxds32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmda32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmsda32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmsxda32, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmxda32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smbb32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smbt32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smtt32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smdrs32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smds32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smxds32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmabb32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmabt32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmadrs32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmads32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmatt32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmaxda32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmaxds32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmda32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmsda32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmsxda32, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmxda32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smbb32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smbt32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smdrs32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smds32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smtt32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smxds32, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_clrs32, int32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_clz32, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_pkbb32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_pkbt32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_pktb32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_pktt32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_sll32, uint32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_srl32, uint32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_srl32_u, uint32x2_t, const uint32_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_uadd32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_uclip32, int32x2_t, uint32_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ucras32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ucrsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ukadd32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ukcras32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ukcrsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ukstas32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ukstsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_uksub32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_umax32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_umin32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_uradd32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_urcras32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_urcrsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_urstas32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_urstsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ursub32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ustas32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_ustsa32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_usub32, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint64_t, add32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, cras32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, crsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, kabs32, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kadd32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kcras32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kcrsa32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kdmabb16, int64_t, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, kdmabt16, int64_t, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, kdmatt16, int64_t, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, kdmbb16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, kdmbt16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, kdmtt16, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, ksll32, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (int64_t, kslra32, int64_t, int32_t)
CREATE_RVP_INTRINSIC (int64_t, kslra32_u, int64_t, int32_t)
CREATE_RVP_INTRINSIC (int64_t, kstas32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kstsa32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, ksub32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (uint64_t, pkbb32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, pkbt32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, pktb32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, pktt32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, radd32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rcras32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rcrsa32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rstas32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rstsa32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rsub32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, sll32, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (int64_t, smax32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smin32, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, sra32, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (int64_t, sra32_u, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (int64_t, srl32, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (int64_t, srl32_u, int64_t, const uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, stas32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, stsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, sub32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukadd32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukcras32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukcrsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukstas32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukstsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, uksub32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, umax32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, umin32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, uradd32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, urcras32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, urcrsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, urstas32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, urstsa32, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ursub32, uint64_t, uint64_t)
#endif

#if defined(__riscv_zpsf)

#if !defined(__riscv_zbpbo)
/* wext/wexti are forbidden with using zbpbo subextension */
CREATE_RVP_INTRINSIC (intXLEN_t, wext, uint64_t, const uint32_t)
#endif

CREATE_RVP_INTRINSIC (int16x4_t, v_smul8, int8x4_t, int8x4_t)
CREATE_RVP_INTRINSIC (int16x4_t, v_smulx8, int8x4_t, int8x4_t)
CREATE_RVP_INTRINSIC (int32x2_t, v_smulx16, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC (int64_t, kadd64, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, kmar64, int64_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, kmsr64, int64_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, ksub64, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, mulsr64, int32_t, int32_t)
CREATE_RVP_INTRINSIC (int64_t, radd64, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, rsub64, int64_t, int64_t)
CREATE_RVP_INTRINSIC (int64_t, smal, int64_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalbb, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalbt, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalda, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smaldrs, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalds, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smaltt, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalxda, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smalxds, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smar64, int64_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smslda, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smslxda, int64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (int64_t, smsr64, int64_t, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (uint16x4_t, v_umul8, uint8x4_t, uint8x4_t)
CREATE_RVP_INTRINSIC (uint16x4_t, v_umulx8, uint8x4_t, uint8x4_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_umul16, uint16x2_t, uint16x2_t)
CREATE_RVP_INTRINSIC (uint32x2_t, v_umulx16, uint16x2_t, uint16x2_t)
CREATE_RVP_INTRINSIC (uint64_t, mulr64, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int64_t, smul16, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, smul8, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (int64_t, smulx16, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, smulx8, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, ukadd64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ukmar64, uint64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint64_t, ukmsr64, uint64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint64_t, uksub64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, umar64, uint64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint64_t, umsr64, uint64_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC (uint64_t, umul16, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, umul8, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, umulx16, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, umulx8, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC (uint64_t, uradd64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, ursub64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC_VECTOR (int32x2_t, smul16, int16x2_t, int16x2_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smal, int64_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalbb, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalbt, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalda, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smaldrs, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalds, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smaltt, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalxda, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smalxds, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smslda, int64_t, int16xN_t, int16xN_t)
CREATE_RVP_INTRINSIC_VECTOR (int64_t, smslxda, int64_t, int16xN_t, int16xN_t)
#if __riscv_xlen == 32
CREATE_RVP_INTRINSIC (int64_t, sadd64, int64_t, int64_t)
CREATE_RVP_INTRINSIC (uint64_t, uadd64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (uint64_t, usub64, uint64_t, uint64_t)
CREATE_RVP_INTRINSIC (int64_t, ssub64, int64_t, int64_t)
#else
CREATE_RVP_INTRINSIC (int64_t, v_kmar64, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_kmsr64, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smar64, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (int64_t, v_smsr64, int64_t, int32x2_t, int32x2_t)
CREATE_RVP_INTRINSIC (uint64_t, v_ukmar64, uint64_t, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint64_t, v_ukmsr64, uint64_t, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint64_t, v_umar64, uint64_t, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC (uint64_t, v_umsr64, uint64_t, uint32x2_t, uint32x2_t)
CREATE_RVP_INTRINSIC_ALIAS (int64_t, kmada32, kmar64, int64_t, int64_t, int64_t)
CREATE_RVP_INTRINSIC_ALIAS (int64_t, v_kmada32, v_kmar64, int64_t, int32x2_t, int32x2_t)
#endif
#endif // END OF ZPSF

#if defined(__riscv_zbpbo)
CREATE_RVP_INTRINSIC (uintXLEN_t, rev, uintXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, max, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (intXLEN_t, min, intXLEN_t, intXLEN_t)
CREATE_RVP_INTRINSIC (uintXLEN_t, cmix, uintXLEN_t, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC_ALIAS (uintXLEN_t, rev8h, swap8, uintXLEN_t)
__extension__ extern __inline __attribute__ ((__always_inline__, __gnu_inline__, __artificial__))
uint8xN_t __rv_v_rev8h (uint8xN_t a) {
  return RVP_CONCAT (RVP_VECTOR_BUILTIN_PREFIX, swap8) (a);
}

#if __riscv_xlen == 32
CREATE_RVP_INTRINSIC (uint32_t, fsr, uint32_t, const uint32_t, uint32_t)
CREATE_RVP_INTRINSIC_ALIAS (uint32_t, clz, clz32, uint32_t)
CREATE_RVP_INTRINSIC_ALIAS (uintXLEN_t, pack, pktt16, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC_ALIAS (uintXLEN_t, packu, pkbb16, uintXLEN_t, uintXLEN_t)
#else
CREATE_RVP_INTRINSIC (uint32_t, fsrw, uint32_t, uint32_t, uint32_t)
CREATE_RVP_INTRINSIC_ALIAS (uintXLEN_t, pack, pktt32, uintXLEN_t, uintXLEN_t)
CREATE_RVP_INTRINSIC_ALIAS (uintXLEN_t, packu, pkbb32, uintXLEN_t, uintXLEN_t)
#endif

#endif // END OF __riscv_zbpbo
#endif // END OF _RISCV_RVP_INTRINSIC_H